config/routes.rb
Itag::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :edit, :update, :index] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "restaurants#search"

  resources :cities, :only => [:show, :index] do
    resources :restaurants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "cities#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, :use => :slugged

  attr_accessible :username, :password, :email, :biography, :age, :gender, :location, :admin, :session_token, :photo, :uid, :provider, :image, :auth_token, :activated
  attr_reader :password

  before_validation :ensure_session_token
  before_validation(:ensure_auth_token, on: :create)

  validates :username, :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, :allow_nil => true }
  validates :password_digest, presence: true
  validates :username, :email, uniqueness: true

  has_attached_file :photo, :styles => {
    :big => "100x100#",
    :small => "60x60#"
  }

  has_many :reviews,
  dependent: :destroy

  has_many :rated_restaurants,
  through: :reviews,
  source: :restaurant

  has_many :favorites,
  dependent: :destroy

  has_many :favorite_places,
  through: :favorites,
  source: :restaurant

  has_many :follows,
  class_name: "Follow",
  foreign_key: :followed_id,
  primary_key: :id,
  dependent: :destroy

  has_many :followed,
  class_name: "Follow",
  foreign_key: :follower_id,
  primary_key: :id,
  dependent: :destroy

  has_many :followers,
  through: :follows,
  source: :follower

  has_many :followed_users,
  through: :followed,
  source: :followed

  has_many :vote_tags,
  dependent: :destroy

  has_many :voted_reviews,
  through: :vote_tags,
  source: :review

  def self.find_uid_or_create(auth)

    user = User.find_by_uid(auth[:uid])

    unless user
      if auth[:provider] == 'facebook'
        user = User.create!(
                 uid: auth[:uid],
                 provider: auth[:provider],
                 username: (auth[:info][:nickname] || auth[:info][:first_name]+rand(1..1000).to_s),
                 email: auth[:info][:email],
                 image: auth[:info][:image] + "?type=large",
                 password: SecureRandom::urlsafe_base64(16)
               )
      elsif auth[:provider] == 'twitter'
        user = User.create!(
                 uid: auth[:uid],
                 provider: auth[:provider],
                 username: auth[:info][:nickname],
                 email: "fillmein@right.meow",
                 image: auth[:info][:image].gsub("_normal", ""),
                 password: SecureRandom::urlsafe_base64(16)
               )
      else
        #asdf
      end
    end

    return user
  end


  def self.find_by_credentials(username, password)
    user = (User.find_by_username(username) || User.find_by_email(username))
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def activate!
    self.activated = true
    self.save
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_auth_token
    self.auth_token ||= self.class.generate_session_token
  end

end

app/models/users.rb
class Users < ActiveRecord::Base
  attr_accessible :username, :password, :email, :biography, :age, :gender, :ethnicity, :location, :admin, :session_token
  attr_reader :password

  before_validation :ensure_session_token

  validates :username, :email, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, :allow_nil => true }
  validates :password_digest, presence: true

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_signed_in!, :only => [:show, :index]
  before_filter :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in(@user)
      AuthMailer.signup_email(@user).deliver!
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update_attributes(params[:user])
      redirect_to user_url(@user)
    else
      render :json => @user.errors.full_messages
    end
  end

  def index
    @users = Kaminari.paginate_array(User.all).page(params[:page])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update!" : "Sign up!") %>

<form class="form" action="<%= action %>" method="post" enctype="multipart/form-data">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <h1><%= message %></h1>

  <div class="input">
    <label for="user_username">Username</label>
    <input
       id="user_username"
       name="user[username]"
       type="text"
       value="<%= @user.username %>">

  </div>

  <div class="input">
  <label for="user_email">Email</label>
  <input
     id="user_email"
     name="user[email]"
     type="email"
     value="<%= @user.email %>">
  </div>

  <div class="input">
    <label for="user_password">Password</label>
    <input
       id="user_password"
       name="user[password]"
       type="password">
   </div>

  <div class="input">
    <label for="user_bio">Biography</label><br>
<textarea id="user_bio" name="user[biography]"><%= @user.biography %></textarea>
  </div>

  <div class="input">
  <label for="user_location">Location</label>
  <input
     id="user_location"
     name="user[location]"
     type="text"
     value="<%= @user.location %>">
  </div>

  <div class="input">
  <label for="user_age">Age</label>
  <input
     id="user_age"
     name="user[age]"
     type="text"
     value="<%= @user.age %>">
  </div>

  <div class="input">
  <label for="user_gender">Gender</label>
  <input
     id="user_gender"
     name="user[gender]"
     type="radio"
     value="M" <%= "checked" if @user.gender == "M" %> >M</input>

   <input
      id="user_gender"
      name="user[gender]"
      type="radio"
      value="F">F</input>
  </div>

  <div class="input">
    <label for="user_photo">Upload a photo!</label>
    <input
        id="user_photo"
        name="user[photo]"
        type="file">
  </div>

  <div class="submit">
    <input type="submit" value="<%= message %>">
  </div>
</form>

app/views/users/activate.html.erb
<% user = User.find(params[:user_id]) %>
<h1>
<% if user.auth_token = params[:auth_token] %>
<% current_user.activate! %>
<%= "Account activated!" %>
<% else %>
<%= "Check your email again" %>
<% end %>
</h1>

app/views/users/edit.html.erb
<%= render "form", :user => @user %>

app/views/users/index.html.erb
<div class="content group">

  <h2>Yay, new friends!</h2>

  <ol class="group">
  <% @users.each do |user| %>

  <a href="<%= user_url(user) %>">
    <% if user.photo.file? %>
      <%= image_tag user.photo.url(:small) %>
    <% else %>
      <%= image_tag "http://i.imgur.com/xqtsqlj.png", size: "60x60" %>
    <% end %>
  </a>

    <li class="results">
      <a href="<%= user_url(user) %>">
        <%= user.username %>
      </a>
    </li>

  <% end %>
  </ol>

  <%= paginate @users %>

</div>

app/views/users/new.html.erb
<div class="left group">
  <div class="social">
    <h1>Use social!</h1>
    <a id="facebook" href="/auth/facebook"><img src="http://i.imgur.com/UIbkQV6.png"></a>

    <p>or</p>

    <a id="twitter" href="/auth/twitter"><img src="http://i.imgur.com/JzFd7Qi.png"></a>
  </div>
</div>

<div class="right group">
  <%= render "form", :user => @user %>
</div>

app/views/users/show.html.erb
<div class="prof-content group">

  <h2>Welcome to <%= @user.username %>'s Profile!</h2>
  <br>


  <div class="prof-left group">

    <% if @user.photo.file? %>
      <%= image_tag @user.photo.url(:big) %>
    <% elsif @user.image? %>
      <%= image_tag @user.image, size: "100x100" %>
    <% else %>
      <%= image_tag "http://i.imgur.com/xqtsqlj.png", size: "100x100" %>
    <% end %>

    <br>

    <% if current_user == @user %>
      <%= link_to "Edit Profile", edit_user_url(@user) %>
    <% end %>

    <% unless current_user == @user %>
      <div class="foll <%="is-followed" if current_user.followed_users.include?(@user) %>">
        <%= button_to "FOLLOW", user_follows_url(@user), method: :post, form_class: "follow-button grad_button", remote: true %>
        <%= button_to "UNFOLLOW", user_follow_url(@user), method: :delete, form_class: "unfollow-button grad_button", remote: true %>
      </div>
    <% end %>

    <ul>
      <li>Hometown: <%= @user.location %></li>
      <li>Age: <%= @user.age %></li>
      <li>Gender: <%= @user.gender %></li>
    </ul>

    <h3>Biography:</h3>
    <p><%= @user.biography %></p>

  </div>

  <div class="prof-mid group">
    <h3>Reviews:</h3>
    <%= render "reviews/user", :user => @user %>
  </div>

  <div class="prof-right group">
    <h3>Favorite Places:</h3>
    <%= render "favorites/user", :user => @user %>

    <%= render "follows/user", :user => @user %>
  </div>
</div>

<script>
  // FOLLOWS
  $('.follow-button').on('ajax:send', function(event){
    $('.foll').toggleClass('is-followed');
  });

  $('.unfollow-button').on('ajax:send', function(event){
    $('.foll').toggleClass('is-followed');
  });
</script>