config/routes.rb
Itag::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :edit, :update, :index] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "restaurants#search"

  resources :cities, :only => [:show, :index] do
    resources :restaurants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "cities#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged

  attr_accessible :name, :website, :price, :phone, :street, :city_id, :zip, :open, :category_ids, :photo

  validates :name, :street, :city_id, presence: true

  validates :name, uniqueness: {:scope => :street, :message => "That listing already exists!"}

  has_attached_file :photo, :styles => {
    :big => "250x250>",
    :medium => "100x100#",
    :small => "60x60#"
  }

  paginates_per 5

  include PgSearch
    multisearchable :against => [:name]

  has_many :tags

  has_many :categories,
  through: :tags,
  source: :category,
  dependent: :destroy

  has_many :reviews,
  dependent: :destroy

  has_many :reviewers,
  through: :reviews,
  source: :user

  belongs_to :city

  has_one :state,
  through: :city

  has_many :favorites,
  dependent: :destroy

  has_many :users_who_favorited,
  through: :favorites,
  source: :user

  def average_rating
    total = 0
    count = self.reviews.count

    if count == 0
      return 0
    else
      self.reviews.each do |review|
        total += review.rating
      end

      return (total.to_f / count).round(1)
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :require_signed_in!, :except => [:index]

  def new
    @city = City.find(params[:city_id])
    @restaurant = @city.restaurants.new
  end

  def create
    @city = City.find(params[:city_id])
    @restaurant = @city.restaurants.new(params[:restaurant])

    if @restaurant.save
      redirect_to restaurant_url(@restaurant)
    else
      render :json => @restaurant.errors.full_messages
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(params[:restaurant])
      redirect_to restaurant_url(@restaurant)
    else
      render :json => @restaurant.errors.full_messages
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # Restaurant.includes(:reviews, :categories, :city, :state, :users_who_favorited).find(params[:id])
  end

  def index
    @city = City.find(params[:city_id])

    @restaurants = @city.restaurants.select("restaurants.*, AVG(reviews.rating) AS avg_rating")
                        .joins("LEFT JOIN reviews ON reviews.restaurant_id = restaurants.id")
                        .group("restaurants.id")
                        .order("avg_rating DESC NULLS LAST")
                        .page(params[:page])
                        .per(5)

    @reviews = Review.select("reviews.*")
                     .joins("JOIN restaurants ON reviews.restaurant_id = restaurants.id")
                     .joins("JOIN cities ON cities.id = restaurants.city_id")
                     .where("cities.id = ?", @city.id)
                     .group("reviews.id")
                     .order("reviews.created_at")
                     .last(5)
                     .reverse!
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])

    @restaurant.destroy

    redirect_to restaurants_url
  end

  def search
    @results = PgSearch.multisearch(params[:query])

    if @results.empty?
      return []
    elsif Category.all.include?(@results.first.searchable)
      @category = @results.first.searchable
        .restaurants.where("city_id = ?", params[:city_id])
        .sort!{ |a, b| a.average_rating <=> b.average_rating }
        .reverse!

      @restaurants = Kaminari.paginate_array(@category)
                             .page(params[:page])
                             .per(10)
    else
      @restaurants = @results.map(&:searchable).sort!{ |a, b| a.average_rating <=> b.average_rating }.reverse!

      @restaurants = Kaminari.paginate_array(@restaurants).page(params[:page]).per(10)
    end

    # @restaurants = Restaurant.includes(:categories).where("city_id = ? AND categories.id = ?", params[:city_id], params[:cat_id]).page(params[:page])
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<% action = (restaurant.persisted? ? restaurant_url(restaurant) : city_restaurants_url) %>
<% method = (restaurant.persisted? ? "put" : "post") %>
<% message = (restaurant.persisted? ? "Update Restaurant" : "Add Restaurant") %>

<form class="form" action="<%= action %>" method="post" enctype="multipart/form-data">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

 <h1><%= message %></h1>

  <div class="input">
    <label for="restaurant_name">Restaurant Name</label>
    <input
       id="restaurant_name"
       name="restaurant[name]"
       type="text"
       value="<%= @restaurant.name %>">
  </div>

  <div class="input">
    <label for="restaurant_category">What type of food is served here?</label>

    <% Category.all.each do |category| %>
  <ul class="category group">
     <li><input id="restaurant_category" name="restaurant[category_ids][]" type="checkbox" value="<%= category.id %>" <%= "checked" if @restaurant.categories.include?(category) %>><%= category.name %></option></li>
  </ul>
    <% end %>
    <input type="hidden" name="restaurant[category_ids][]" value="">
  </div>

  <br><br><br><br>

  <div class="input">
    <label for="restaurant_website">Website</label>
    <input
       id="restaurant_website"
       name="restaurant[website]"
       type="url"
       value="<%= @restaurant.website %>">
  </div>

  <div class="input">
    <label for="restaurant_phone">Phone Number</label>
    <input
       id="restaurant_phone"
       name="restaurant[phone]"
       type="text"
       value="<%= @restaurant.phone %>">
  </div>

  <div class="input">
    <label for="restaurant_price">Price Range</label>

  <input
     id="restaurant_price"
     name="restaurant[price]"
     type="radio"
     value="$" <%= "checked" if @restaurant.price == "$" %> >$</input>
  <input
    id="restaurant_price"
    name="restaurant[price]"
    type="radio"
    value="$$" <%= "checked" if @restaurant.price == "$$" %> >$$</input>
  <input
     id="restaurant_price"
     name="restaurant[price]"
     type="radio"
     value="$$$" <%= "checked" if @restaurant.price == "$$$" %> >$$$</input>
   <input
      id="restaurant_price"
      name="restaurant[price]"
      type="radio"
      value="$$$$" <%= "checked" if @restaurant.price == "$$$$" %> >$$$$</input>
  </div>

  <div class="input">
    <label for="restaurant_street">Street</label>
    <input
       id="restaurant_street"
       name="restaurant[street]"
       type="text"
       value="<%= @restaurant.street %>">
  </div>

  <div class="input">
    <label for="restaurant_city">Location</label>
    <select class="searchSelect" id="restaurant_city" name="restaurant[city_id]">
      <% City.all.each do |city| %>
      <option value="<%= city.id %>" <%= "selected" if @restaurant.city_id == city.id %>><%= city.name %>, <%= city.state.name %></option>
      <% end %>
    </select>
  </div>

  <div class="input">
    <label for="restaurant_zip">Zip Code</label>
    <input
       id="restaurant_zip"
       name="restaurant[zip]"
       type="text"
       value="<%= @restaurant.zip %>">
  </div>

  <div class="input">
    <label for="restaurant_open">Closed?</label>
    Yes<input
       id="restaurant_open"
       name="restaurant[open]"
       type="radio"
       value="false" <%= "checked" if @restaurant.open == false %>>
     </input>

     No<input
        id="restaurant_open"
        name="restaurant[open]"
        type="radio"
        value="true" <%= "checked" if @restaurant.open == true %>>
      </input>
  </div>

  <div class="input">
    <label for="restaurant_photo">Add a photo for this restaurant!</label>
    <input
        id="restaurant_photo"
        name="restaurant[photo]"
        type="file">
  </div>

  <div class="submit">
    <input type="submit" value="<%= message %>">
  </div>
</form>
<br>

app/views/restaurants/edit.html.erb
<%= render "form", :restaurant => @restaurant %>

app/views/restaurants/index.html.erb
<div class="city-switch">
  <form id="page-changer" action="" method="post">
    <select onChange="window.location.replace(this.options[this.selectedIndex].value)">
      <option value="">Go to city...</option>
      <% City.all.each do |city| %>
        <option value="<%= city_restaurants_url(city) %>">
          <%= city.name %>, <%= city.state.name %>
        </option>
      <% end %>
    </select>
  </form>
</div>

<div class="content group">

  <h2>What's popular in <%= @city.name %>, <%= @city.state.name %></h2>
  <%= link_to "Add a new restaurant", new_city_restaurant_url(@city) %>

  <ol class="group">
  <% @restaurants.each_with_index do |restaurant, i| %>

  <a href="<%= restaurant_url(restaurant) %>">
    <% if restaurant.photo.file? %>
      <%= image_tag restaurant.photo.url(:small) %>
    <% else %>
      <%= image_tag "http://i.imgur.com/xqtsqlj.png", size: "60x60" %>
    <% end %>
  </a>

    <li class="results">
      <%= (5*(@restaurants.current_page-1))+i+1 %>.
      <a href="<%= restaurant_url(restaurant) %>">
        <%= restaurant.name %>
      </a>
      (Average Rating: <%= restaurant.avg_rating.to_f.round(1) %>)
    </li>

  <% end %>
  </ol>

  <%= paginate @restaurants %>

  <hr>

  <h2>Recent Reviews</h2>
  <ul class="recent-reviews-<%= @city.id %> group">
    <% @reviews.each do |review| %>
     <li class="recent-<%= @city.id %>"><%= render partial: "reviews/pusherform", locals: {review: review} %></li>
    <% end %>
  </ul>

</div>

<script src="http://js.pusher.com/2.1/pusher.min.js"></script>
<script>
  var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>');

  var channel = pusher.subscribe('reviews');

  channel.bind('new-review', function(data) {
    var city = $(data).attr('data-id');
 $(data).hide().prependTo(".recent-reviews-"+city).slideDown("slow");

    $(".recent-"+city).last().remove();
  });
</script>

app/views/restaurants/new.html.erb
<%= render "form", :restaurant => @restaurant %>

app/views/restaurants/search.html.erb
<div class="content group">
  <h1>SEARCH RESULTS!</h1>

  <% if (!@category.nil? || !@restaurants.nil?) %>

    <ol class="group">
    <% @restaurants.each_with_index do |restaurant, i| %>
      <% if restaurant.photo.file? %>
        <%= image_tag restaurant.photo.url(:medium) %>
      <% end %>
      <li class="search_results">
        <%= (10*(@restaurants.current_page-1))+i+1 %>.
        <a href="<%= restaurant_url(restaurant) %>">
        <%= restaurant.name %>
        </a>
        (Average Rating: <%= restaurant.average_rating %>)
      </li>
    <% end %>
    </ol>
    <%= paginate @restaurants %>

  <% else %>
    <%= "No results found!" %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="rest-content group">

  <section class="modal">
    <article class="modal-box">
      <span class="modal-close-button">&times;</span>
      <div id="modal-container">

        <form class="form" action="<%= restaurant_reviews_url(@restaurant) %>" method="post" data-remote="true" id="jsform">
          <input
             name="authenticity_token"
             type="hidden"
             value="<%= form_authenticity_token %>">

         <h1>New Review!</h1>

         <div class="input">
          <label for="review_rating">Rating</label>
          <select id="review_rating" name="review[rating]">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
         </div>

         <div class="input">
          <label for="review_email">Review Title</label>
          <input id="review_title" name="review[title]" type="text" value="">
          <br>
        </div>

        <div class="input">
          <label for="review_body">Review Body</label><br>
        <textarea id="review_body" name="review[body]"></textarea>
        </div>

         <div class="submit">
          <input id="submit" type="submit" value="Create review!">
         </div>
        </form>

      </div>
    </article>
  </section>

  <div class="rest-left group">
    <div class="rest-info">

      <div class="rest-photo">
      <% if @restaurant.photo.file? %>
        <%= image_tag @restaurant.photo.url(:big) %>
      <% else %>
        <%= image_tag "http://i.imgur.com/xqtsqlj.png", size: "100x100" %>
      <% end %>
      </div>


    <h2>
      <%= @restaurant.name %>
      <%= "(CLOSED)" if @restaurant.open == false %>
    </h2>

    <% if current_user && current_user.admin == true %>
      (<%= link_to "Edit Listing", edit_restaurant_url(@restaurant) %>)
    <% end %>
    <br>

    <div class="favs <%="is-favorite" if current_user.favorite_places.include?(@restaurant) %>">
      <%= button_to "FAVORITE", restaurant_favorites_url(@restaurant), method: :post, form_class: "favorite-button grad_button", remote: true %>
      <%= button_to "UNFAVORITE", restaurant_favorite_url(@restaurant), method: :delete, form_class: "unfavorite-button grad_button", remote: true %>
    </div>

  <br>

  Average Rating: <%= @restaurant.average_rating %> (<%= @restaurant.reviews.count %> reviews)

  <br>

  Categories:
  <br>
  <ul>
  <% @restaurant.categories.each do |category| %>
    <li><%= category.name %></li>
  <% end %>
  </ul>

  <!-- RESTAURANT INFO -->

  <h3>Restaurant Info</h3>
  <ul>
    <% unless @restaurant.website.empty? %>
      <li><%= link_to @restaurant.website, @restaurant.website %> </li>
    <% end %>
    <% unless @restaurant.phone.empty? %>
      <li> <%= @restaurant.phone %> </li>
    <% end %>
    <% unless @restaurant.price.nil? %>
      <li> <%= @restaurant.price %> </li>
    <% end %>
    <li id="address"><%= @restaurant.street %>, <%= @restaurant.city.name %>, <%= @restaurant.state.name %></li>
    <% unless @restaurant.zip.empty? %>
      <%= @restaurant.zip %>
    <% end %>
  </ul>

  <!-- REVIEWS -->
  <h3>Reviews</h3>

  <% if current_user && @restaurant.open == true && !current_user.rated_restaurants.include?(@restaurant) %>
    <a href="#" class="show-modal">Write a new review!</a>
    <%#= link_to "Write a review!", new_restaurant_review_url(@restaurant), class: "new-review" %>
  <% end %>


  <br>
<div class="reviews">
  <%= render "reviews/index", :restaurant => @restaurant %>
</div>
    </div>
  </div>


  <!-- MAPS IMAGE -->

  <div class="rest-right group">

    <div id="map-canvas">

    </div>
  </div>
</div>


<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA1vzTzS0JGhNkO2rWAopHhtIrFZBImTZ4&sensor=false">
</script>

<script>

// NEW REVIEW MODAL

$(document).ready(function(){

  window.modal = {
    show: function(){
      $("body").addClass("has-active-modal");
    },
    hide: function(){
      $("body").removeClass("has-active-modal");
    }
  };

  $("body").on("click", ".show-modal", function(event){
    event.preventDefault();
    window.modal.show();
  });

  $(".modal").on("click", function(event){

    $target = $(event.target);

    if($target.is(".modal") || $target.is(".modal-close-button")){
      event.preventDefault();
      window.modal.hide();
    }
  });

  $("#jsform").on("ajax:send", function(event){
    $("#submit").attr('disabled', 'true');
  });

  $("#jsform").on("ajax:success", function(event, data){
    window.modal.hide();
    $(".reviews").prepend(data);
    $(".show-modal").remove();
  });

});

// GOOGLE MAPS

  function initialize() {
    var address = $('#address').html();
    var geocoder = new google.maps.Geocoder();

    geocoder.geocode({address: address}, function(results, status) {
      var mapOptions = {
        center: new google.maps.LatLng(results[0].geometry.location['e'], results[0].geometry.location['d']),
        zoom: 16
      };

      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });

      var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
        map: map,
        position: results[0].geometry.location
      });

    });
  };

  google.maps.event.addDomListener(window, 'load', initialize);

  // FAVORITES
  $('.favorite-button').on('ajax:send', function(event){
    $('.favs').toggleClass('is-favorite');
  });

  $('.unfavorite-button').on('ajax:send', function(event){
    $('.favs').toggleClass('is-favorite');
  });
</script>