config/routes.rb
Itag::Application.routes.draw do
  resources :users, :only => [:create, :new, :show, :edit, :update, :index] do
    resources :follows, :only => [:create, :destroy]
    get 'activate'
  end

  resource :session, :only => [:create, :destroy, :new]

  resources :restaurants, :except => [:index, :new, :create] do
    resources :reviews, :only => [:create, :new, :index]
    resources :favorites, :only => [:create, :destroy]
  end

  get 'search' => "restaurants#search"

  resources :cities, :only => [:show, :index] do
    resources :restaurants, :only => [:index, :new, :create]
  end

  resources :reviews, :only => [:show, :edit, :update, :destroy] do
    resources :vote_tags, :only => [:create, :destroy]
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  root :to => "cities#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="icon" type="image/png" href="http://i.imgur.com/QwzZ4bE.png">
<html>
<head>
  <title>Is that any good?</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav class="top-nav group">
    <div class="container group">

      <div class="info">
        <ul>
          <strong>
          <% if signed_in? %>
            <li>User:
              <%= link_to current_user.username, user_url(current_user) %>
              <%= "(admin)" if current_user.admin == true %>
            </li>
            <li><%= link_to "Sign Out", session_url, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_session_url %></li>
            <li><%= link_to "Sign up", new_user_url %></li>
          <% end %>
          </strong>
        </ul>
      </div>

      <div class="logo">
        <a href="/">
          <img src="http://i.imgur.com/juvmlpu.png">
        </a>
      </div>

      <div class="search group">
        <form class="group" action="<%= search_url %>" method="get">
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

        <div class="search-box group">
          <label>Find</label>
          <input type="text" name="query" value="">
        </div>

        <div class="search-box group">
          <label>In</label>
          <select name="city_id" class="search-select">
          <% City.all.each do |city| %>
            <option value="<%= city.id %>">
              <%= city.name %>, <%= city.state.name %>
            </option>
          <% end %>
          </select>
        </div>

        <div class="search-submit group">
          <input id="find" type="submit" value="">
        </div>
        </form>

        <ul class="mini-nav group">
          <%= link_to "<li>Home</li>".html_safe, "/" %>
          <% if signed_in? %>
            <%= link_to "<li>My Profile</li>".html_safe, user_url(current_user)%>
          <% else %>
            <%= link_to "<li>My Profile</li>".html_safe, new_session_url %>
          <% end %>
            <%= link_to "<li>Find Friends</li>".html_safe, users_url %>
        </ul>
      </div>

    </div>
  </nav>
</header>

<main>
  <div class="main group">

    <%= yield %>

  </div>
</main>


<footer class="group">
  <div class="footer group">

    Copyright © 2014 :D

  </div>
</footer>

</body>
</html>